name: Verbesserung vorschlagen
description: Eine Idee oder Verbesserung
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Anlass
      description: Was möchtest du mit Ratslotse machen, und was fehlt dir dafür?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Vorgeschlagene Lösung
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen (optional)
